source "https://rubygems.org"

gem "sinatra", "~> 4.1"
gem "sequel", "~> 5.84"
gem "sqlite3", ">= 2.9.5", "< 3.0"
gem "rackup", "~> 2.1"
gem "puma", "~> 7.0"

gem "active_version", path: "../.."

group :test do
  gem "rspec", "~> 3.13"
  gem "capybara", "~> 3.40"
  gem "capybara-playwright-driver", require: false
end
